package ionix.Data;


public enum AutoGeneratedKey {

    CLOSE_CURRENT_RESULT(1),

    KEEP_CURRENT_RESULT(2),

    CLOSE_ALL_RESULTS(3),

    SUCCESS_NO_INFO(-2),

    EXECUTE_FAILED(-3),

    RETURN_GENERATED_KEYS(1),

    NO_GENERATED_KEYS(2);

    private final int value;
    AutoGeneratedKey(int value){
        this.value = value;
    }
    public final int getValue(){
        return this.value;
    }
}