package ionix.Data;


public class EntitySqlQueryBuilderResult {
    public final SqlQuery Query;
    public final AutoGeneratedKey Key;
    public final FieldMetaData Identity;
    public final int DivideFactor;//templateQuery.getParameters().size

    public EntitySqlQueryBuilderResult(SqlQuery query, AutoGeneratedKey key, FieldMetaData identity, int divideFactor){
        this.Query = query;
        this.Key = key;
        this.Identity = identity;
        this.DivideFactor = divideFactor;
    }
}
