package ionix.Data;

import ionix.Data.*;
import ionix.Utils.*;

import java.util.*;


public abstract class EntitySqlQueryBuilderInsert implements EntitySqlQueryBuilder {
    private HashSet<String> insertFields;
    protected HashSet<String > getInsertFields(){
        return this.insertFields;
    }
    public void setInsertFields(HashSet<String> insertFields){
        this.insertFields = insertFields;
    }

    @Override
    public abstract Triplet<SqlQuery, AutoGeneratedKey, FieldMetaData> createQuery(Object entity, EntityMetaData metaData);
}
