package ionix.Data;

import ionix.Utils.Triplet;

public interface EntitySqlQueryBuilder {
    Triplet<SqlQuery, AutoGeneratedKey, FieldMetaData> createQuery(Object entity, EntityMetaData metaData);
}
